export const UDEMY_FEED_CARDS = [
  {
    title: 'Learn Artificial Intelligence: AI For Everyone',
    instructor: 'Jarvis: The AI',
    rating: 4.8,
    totalRatings: 1234,
    salePrice: 12.99,
    actualPrice: 19.99,
    thumbnail: 'https://img-a.udemycdn.com/course/240x135/705264_caa9_11.jpg',
    tag: 'Bestseller',
  },
  {
    title: 'Learn Artificial Intelligence: AI For Everyone',
    instructor: 'Jarvis: The AI',
    rating: 4.8,
    totalRatings: 1234,
    salePrice: 12.99,
    actualPrice: 19.99,
    thumbnail: 'https://img-a.udemycdn.com/course/240x135/705264_caa9_11.jpg',
    tag: 'Highest Rated',
  },
  {
    title: 'Learn Artificial Intelligence: AI For Everyone',
    instructor: 'Jarvis: The AI',
    rating: 4.8,
    totalRatings: 1234,
    salePrice: 12.99,
    actualPrice: 19.99,
    thumbnail: 'https://img-a.udemycdn.com/course/240x135/705264_caa9_11.jpg',
    tag: 'You are Awesome',
  },
  {
    title: 'Learn Artificial Intelligence: AI For Everyone',
    instructor: 'Jarvis: The AI',
    rating: 4.8,
    totalRatings: 1234,
    salePrice: 12.99,
    actualPrice: 19.99,
    thumbnail: 'https://img-a.udemycdn.com/course/240x135/705264_caa9_11.jpg',
    tag: 'Bestseller',
  },
  {
    title: 'Learn Artificial Intelligence: AI For Everyone',
    instructor: 'Jarvis: The AI',
    rating: 4.8,
    totalRatings: 1234,
    salePrice: 12.99,
    actualPrice: 19.99,
    thumbnail: 'https://img-a.udemycdn.com/course/240x135/705264_caa9_11.jpg',
    tag: 'Highest Rated',
  },
  {
    title: 'Learn Artificial Intelligence: AI For Everyone',
    instructor: 'Jarvis: The AI',
    rating: 4.8,
    totalRatings: 1234,
    salePrice: 12.99,
    actualPrice: 19.99,
    thumbnail: 'https://img-a.udemycdn.com/course/240x135/705264_caa9_11.jpg',
    tag: 'Highest Rated',
  },
];
